// Embeds the Swift hotkey helper into a TypeScript module so it ships inside the single-file CLI bundle.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'desktop');
const source = readFileSync(join(root, 'spotlight-hud.swift'), 'utf8');
const out =
  '// Generated by scripts/embed-swift.mjs from spotlight-hud.swift. Do not edit; run `npm run build -w @remote-hands/daemon`.\n' +
  `export const SPOTLIGHT_SWIFT_SOURCE: string = ${JSON.stringify(source)};\n`;
const target = join(root, 'spotlight-source.generated.ts');
let current = '';
try {
  current = readFileSync(target, 'utf8');
} catch {}
if (current !== out) writeFileSync(target, out);
